/*
APELLIDO y OFICIO de los empleados sin comisión. 
*/

SELECT APELLIDO, OFICIO
FROM VENTAS.EMPLEADOS
WHERE
    COMISION IS NULL
    OR COMISION = 0;

---

SELECT APELLIDO, OFICIO FROM EMPLEADOS WHERE IFNULL(COMISION, 0) = 0