/*
Visualizar el departamento con más empleados
*/

SELECT COUNT(*) AS 'NÚMERO DE EMPLEADOS', D.DEP_NO, D.DNOMBRE, D.LOCALIDAD
FROM VENTAS.EMPLEADOS E
    INNER JOIN VENTAS.DEPARTAMENTOS D ON D.DEP_NO = E.DEP_NO
GROUP BY
    D.DEP_NO
ORDER BY COUNT(*) DESC
LIMIT 1;