/*
Visualizar el departamento con más personal del oficio ‘empleado'
*/

SELECT DNOMBRE, COUNT(*) AS 'EMPLEADOS'
FROM VENTAS.EMPLEADOS E
    INNER JOIN VENTAS.DEPARTAMENTOS D ON E.DEP_NO = D.DEP_NO
WHERE
    OFICIO = 'EMPLEADO'
GROUP BY
    DNOMBRE
ORDER BY 2 DESC
LIMIT 1;

SELECT DNOMBRE, COUNT(*) AS 'EMPLEADOS'
FROM VENTAS.EMPLEADOS E, VENTAS.DEPARTAMENTOS D
WHERE
    E.DEP_NO = D.DEP_NO
    AND OFICIO = 'EMPLEADO'
GROUP BY
    DNOMBRE
ORDER BY 2 DESC
LIMIT 1;