/*
Mostar la descripción y precio de los productos vendidos por el vendedor “ALONSO”
*/

-- Consulta multitabla
SELECT P.DESCRIPCION, P.PRECIO_ACTUAL
FROM VENTAS.PRODUCTOS P, VENTAS.PEDIDOS PED, VENTAS.CLIENTES C, VENTAS.EMPLEADOS E
WHERE
    P.PRODUCTO_NO = PED.PRODUCTO_NO
    AND PED.CLIENTE_NO = C.CLIENTE_NO
    AND C.VENDEDOR_NO = E.EMP_NO
    AND E.APELLIDO = 'ALONSO';

-- INNER JOIN
SELECT PR.DESCRIPCION, PR.PRECIO_ACTUAL
FROM VENTAS.PRODUCTOS PR
    INNER JOIN VENTAS.PEDIDOS P ON PR.PRODUCTO_NO = P.PRODUCTO_NO
    INNER JOIN VENTAS.CLIENTES C ON P.CLIENTE_NO = C.CLIENTE_NO
    INNER JOIN VENTAS.EMPLEADOS E ON C.VENDEDOR_NO = E.EMP_NO
    AND E.APELLIDO = 'ALONSO';