/*
Apellido, salario y localidad de los empleados de Sevilla y Valencia
*/

-- Consulta multitabla
SELECT E.APELLIDO, E.SALARIO, D.LOCALIDAD
FROM VENTAS.EMPLEADOS E, VENTAS.DEPARTAMENTOS D
WHERE
    E.DEP_NO = D.DEP_NO
    AND D.LOCALIDAD IN ('SEVILLA', 'VALENCIA');

-- INNER JOIN
SELECT E.APELLIDO, E.SALARIO, D.LOCALIDAD
FROM VENTAS.EMPLEADOS E
    INNER JOIN VENTAS.DEPARTAMENTOS D ON E.DEP_NO = D.DEP_NO
WHERE
    D.LOCALIDAD = 'SEVILLA'
    OR D.LOCALIDAD = 'VALENCIA';