/*
Para cada empleado indicar el nombre del empleado y el nombre de su jefe
*/

-- Consulta multitabla
SELECT E1.APELLIDO, E2.APELLIDO AS 'JEFE'
FROM VENTAS.EMPLEADOS E1, VENTAS.EMPLEADOS E2
WHERE
    E1.EMP_NO = E2.DIRECTOR;

-- INNER JOIN
SELECT E1.APELLIDO, E2.APELLIDO AS 'JEFE'
FROM VENTAS.EMPLEADOS E1
    INNER JOIN VENTAS.EMPLEADOS E2 ON E1.EMP_NO = E2.DIRECTOR;