/*
Para cada pedido indicar el nombre del cliente y el nombre del producto comprado
*/

-- Consulta multitabla
SELECT C.NOMBRE, PR.DESCRIPCION
FROM VENTAS.CLIENTES C, VENTAS.PEDIDOS P, VENTAS.PRODUCTOS PR
WHERE
    C.CLIENTE_NO = P.CLIENTE_NO
    AND P.PRODUCTO_NO = PR.PRODUCTO_NO;

-- INNER JOIN
SELECT C.NOMBRE, PR.DESCRIPCION
FROM VENTAS.PEDIDOS P
    INNER JOIN VENTAS.CLIENTES C ON P.CLIENTE_NO = C.CLIENTE_NO
    INNER JOIN VENTAS.PRODUCTOS PR ON P.PRODUCTO_NO = PR.PRODUCTO_NO;