/*
Obtén un listado de los productos vendidos por cada empleado (apellido del empleado y descripción y
precio actual de los productos).
*/

-- Consulta multitabla
SELECT DISTINCT
    E.APELLIDO,
    PR.DESCRIPCION,
    PR.PRECIO_ACTUAL
FROM VENTAS.PRODUCTOS PR, VENTAS.PEDIDOS P, VENTAS.CLIENTES C, VENTAS.EMPLEADOS E
WHERE
    PR.PRODUCTO_NO = P.PRODUCTO_NO
    AND P.CLIENTE_NO = C.CLIENTE_NO
    AND C.VENDEDOR_NO = E.EMP_NO;

-- INNER JOIN
SELECT DISTINCT
    E.APELLIDO,
    PR.DESCRIPCION,
    PR.PRECIO_ACTUAL
FROM VENTAS.PRODUCTOS PR
    INNER JOIN VENTAS.PEDIDOS P ON PR.PRODUCTO_NO = P.PRODUCTO_NO
    INNER JOIN VENTAS.CLIENTES C ON P.CLIENTE_NO = C.CLIENTE_NO
    INNER JOIN VENTAS.EMPLEADOS E ON C.VENDEDOR_NO = E.EMP_NO;