/*
Comprueba el número de veces que ha sido vendido cada producto
*/

SELECT PR.DESCRIPCION, COUNT(P.PRODUCTO_NO) AS 'VENTAS', P.PRODUCTO_NO, SUM(P.UNIDADES) as 'UNIDADES VENDIDAS'
FROM VENTAS.PEDIDOS P
    INNER JOIN VENTAS.PRODUCTOS PR ON P.PRODUCTO_NO = PR.PRODUCTO_NO
GROUP BY
    P.PRODUCTO_NO;