/*
Comprueba qué producto ha sido vendido un mayor número de veces
*/

-- Consulta multitabla
SELECT P.PRODUCTO_NO, PR.DESCRIPCION, COUNT(P.PEDIDO_NO) AS 'VENTAS', SUM(P.UNIDADES) AS 'UNIDADES VENDIDAS'
FROM VENTAS.PEDIDOS P, VENTAS.PRODUCTOS PR
WHERE
    PR.PRODUCTO_NO = P.PRODUCTO_NO
GROUP BY
    P.PRODUCTO_NO
ORDER BY SUM(P.UNIDADES) DESC
LIMIT 1;

-- INNER JOIN
SELECT P.PRODUCTO_NO, PR.DESCRIPCION, COUNT(P.PEDIDO_NO) AS 'VENTAS', SUM(P.UNIDADES) AS 'UNIDADES VENDIDAS'
FROM VENTAS.PEDIDOS P
    INNER JOIN VENTAS.PRODUCTOS PR ON PR.PRODUCTO_NO = P.PRODUCTO_NO
GROUP BY
    P.PRODUCTO_NO
ORDER BY SUM(P.UNIDADES) DESC
LIMIT 1;