/*
Cuántos pedidos ha realizado el cliente DISTRIBUCIONES GOMEZ. 
*/

SELECT COUNT(P.PEDIDO_NO) AS 'NÚMERO DE PEDIDOS'
FROM VENTAS.CLIENTES C, VENTAS.PEDIDOS P
WHERE
    C.CLIENTE_NO = P.CLIENTE_NO
    AND C.NOMBRE = 'DISTRIBUCIONES GOMEZ'
GROUP BY
    C.NOMBRE;