/*
Indicar el nombre y la fecha en que se ha vendido por última vez 
cada producto siempre y cuando el importe total de ventas de ese 
producto sea superior a 100.
*/

-- Consulta multitabla
SELECT PR.DESCRIPCION, MAX(P.FECHA_PEDIDO) AS 'FECHA DE LA ÚLTIMA VENTA'
FROM VENTAS.PEDIDOS P, VENTAS.PRODUCTOS PR
WHERE
    P.PRODUCTO_NO = PR.PRODUCTO_NO
GROUP BY
    PR.DESCRIPCION
HAVING
    SUM(PR.PRECIO_ACTUAL * P.UNIDADES) > 100;

-- INNER JOIN
SELECT PR.DESCRIPCION, MAX(P.FECHA_PEDIDO) AS 'FECHA DE LA ÚLTIMA VENTA'
FROM VENTAS.PEDIDOS P
    INNER JOIN VENTAS.PRODUCTOS PR ON P.PRODUCTO_NO = PR.PRODUCTO_NO
GROUP BY
    PR.DESCRIPCION
HAVING
    SUM(PR.PRECIO_ACTUAL * P.UNIDADES) > 100;