/*
El pedido 1001 no ha sido pagado, por ese motivo debemos añadir al debe del
cliente el importe del pedido
*/

-- Consulta multitabla
UPDATE VENTAS.PRODUCTOS PR, VENTAS.PEDIDOS P, VENTAS.CLIENTES C
SET
    C.DEBE = C.DEBE + (PR.PRECIO_ACTUAL * P.UNIDADES)
WHERE
    P.PEDIDO_NO = 1001
    AND PR.PRODUCTO_NO = P.PRODUCTO_NO
    AND P.CLIENTE_NO = C.CLIENTE_NO;

-- INNER JOIN
UPDATE VENTAS.PEDIDOS P
INNER JOIN VENTAS.CLIENTES C ON P.CLIENTE_NO = C.CLIENTE_NO
INNER JOIN VENTAS.PRODUCTOS PR ON P.PRODUCTO_NO = PR.PRODUCTO_NO
SET
    C.DEBE = C.DEBE + (P.UNIDADES * PR.PRECIO_ACTUAL)
WHERE
    P.PEDIDO_NO = 1001;

SELECT * FROM VENTAS.CLIENTES;