/*
Crea una nueva tabla de “EMP_CONT” con la misma estructura que la tabla de empleados, e inserta en
ella los empleados del departamento de contabilidad.
*/

-- Varias consultas
CREATE TABLE VENTAS.EMP_CONT (
    EMP_NO SMALLINT(4) NOT NULL, APELLIDO VARCHAR(20), OFICIO VARCHAR(20), DIRECTOR SMALLINT(4), FECHA_ALTA DATE, SALARIO FLOAT(8, 2), COMISION FLOAT(8, 2), DEP_NO SMALLINT(4), TELEFONO VARCHAR(15), PRIMARY KEY (EMP_NO), INDEX FK_EMP_DIRECTOR (DIRECTOR ASC), INDEX FK_EMP_CONT_DEP_NO (DEP_NO ASC), CONSTRAINT FK_EMP_CONT_DEP_NO FOREIGN KEY (DEP_NO) REFERENCES DEPARTAMENTOS (DEP_NO) ON UPDATE CASCADE
);

INSERT INTO
    VENTAS.EMP_CONT
SELECT *
FROM VENTAS.EMPLEADOS
WHERE
    DEP_NO = (
        SELECT DEP_NO
        FROM VENTAS.DEPARTAMENTOS
        WHERE
            DNOMBRE = 'CONTABILIDAD'
    );

-- Una consulta
CREATE TABLE EMP_CONT AS
SELECT *
FROM VENTAS.EMPLEADOS
WHERE
    DEP_NO = (
        SELECT DEP_NO
        FROM VENTAS.DEPARTAMENTOS
        WHERE
            DNOMBRE = 'CONTABILIDAD'
    );